stackoverflow/authenticate/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "authenticate"
urlpatterns = [
    path('', views.home_page, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('ask/', views.ask_question_view, name='ask-question'),
    path('question/<int:question_id>/', views.question_detail, name='question-detail'),
    path('saved/', views.saved_view, name='saved-view'),
    
    path('edit/', views.edit_view, name='edit-profile'),
    path('profile/', views.profile_view, name='profile-view'),
    
    path('logout/', views.logout_view, name="logout")
]

stackoverflow/stackoverflow/urls.py
from django.contrib import admin
from django.urls import path, include

from stackoverflow.settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static

urlpatterns = [
    path('', include('authenticate.urls')),
    path('admin/', admin.site.urls),
] + static(MEDIA_URL, document_root = MEDIA_ROOT)

stackoverflow/authenticate/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Title = models.CharField(max_length=255)
    Description = models.TextField()
    CreatedAt = models.DateTimeField(auto_now_add=True)
    what_you_try = models.TextField()
    Tags = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    
    def __str__(self) -> str:
        # return super().__str__()
        return self.Title

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Content = models.TextField()
    CreatedAt = models.DateTimeField(auto_now_add=True)
    Likes = models.IntegerField(default=0)
    flag = models.BooleanField(default=True)
    
    class Meta:
        ordering = ["-CreatedAt"]

class Comment(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True, blank=True)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Content = models.TextField()
    CreatedAt = models.DateTimeField(auto_now_add=True)
    
    
class QuestionVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    vote_type = models.CharField(max_length=4)

    class Meta:
        unique_together = ('user', 'question')
        
class AnswerVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    vote_type = models.CharField(max_length=4)

    class Meta:
        unique_together = ('user', 'answer')
        
class UserInformation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Name = models.CharField(max_length=30, blank=True)
    Title = models.CharField(max_length=20, blank=True)
    Profile_image = models.ImageField(upload_to='profile_pics', blank=True, null=True)
    Location = models.CharField(max_length=70, blank=True)
    About = models.TextField(blank=True)
    CreatedAt = models.DateField(auto_now_add=True)
    Website_link = models.CharField(max_length=70, blank=True)
    Github_link = models.CharField(max_length=70, blank=True)
    Twitter_link = models.CharField(max_length=70, blank=True)
    
class BookMarked(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True, blank=True)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True, blank=True)
    isBookMarked = models.BooleanField(default=False)
    

stackoverflow/authenticate/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1']
        
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields.pop('password2')

# class EmailAuthenticationForm(AuthenticationForm):
#     email = forms.EmailField(widget=forms.TextInput(attrs={'autofocus': True}))

#     def clean_username(self):
#         return self.cleaned_data['email']

class QuestionForm(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = [
            'Title',
            'Description',
            'what_you_try',
            'Tags'
        ]

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['Content'] 
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = ['Content']

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = models.UserInformation
        fields = [
            'Name',
            'Title',
            'Profile_image',
            'Location',
            'About',
            'Website_link',
            'Github_link',
            'Twitter_link',
        ]

stackoverflow/authenticate/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from .forms import RegistrationForm, QuestionForm
from django.db.models import Count, Q
from . import models
from . import forms


# Create your views here.

def register(request):
    if(request.user.is_authenticated):
        return redirect('authenticate:home')
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  
            # modelname.objects.create(user = req.user)
            return redirect('authenticate:home')
    else:
        form = RegistrationForm()
    return render(request, 'register.html', {"form" : form})

def home_page(request):
    user=request.user
    questions = models.Question.objects.annotate(answer_count=Count('answer')).order_by('-CreatedAt')[:20]
    
    if request.method == 'POST':
        input_value = request.POST.get("input-value")
        question_array = models.Question.objects.filter(
    Q(Title__icontains=input_value) | Q(Tags__icontains=input_value)
)

        questions =  question_array
        
    
    for question in questions:
        question.tag_list = [tag.strip() for tag in question.Tags.split(',')]
        
    context = {
        "questions": questions,
        "user" : user,
        # "tags" : tags
    }
    return render(request, "homepage.html", context)


def login_view(request):
    if(request.user.is_authenticated):
        return redirect("authenticate:home")
    error=''
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('authenticate:home')
        else:
            error = "Invalid username/password"
    # else:
    form = AuthenticationForm()

    return render(request, 'login.html', {'form': form, "errors":error})



def ask_question_view(request):
    if(request.user.is_authenticated):
        if request.method == 'POST':
            form = QuestionForm(request.POST)
            if form.is_valid():
                question = form.save(commit=False)
                question.user = request.user
                question.save()
                return redirect('authenticate:home')
        else:
            form = QuestionForm()
        
        return render(request, 'ask-question.html', {'form': form})
    else:
        return redirect("authenticate:login")

def question_detail(request, question_id):
    question = get_object_or_404(models.Question, id=question_id)
    answers = models.Answer.objects.filter(question=question)
    comment_form = forms.CommentForm(request.POST)
    answer_form = forms.AnswerForm(request.POST)
    question.tag_list = question.Tags.split(" ")
    bookmark= None
    if request.user.is_authenticated:
        bookmark = models.BookMarked.objects.filter(user=request.user, question=question).first()
    # question.views += 1
    # question.save()

    if request.method == 'POST' and request.user.is_authenticated:
        input_type = request.POST.get("input_type")
        
        voted_question = models.QuestionVote.objects.filter(user=request.user, question=question).first()
        # print(voted_question)
        
        if input_type in ("up", "down"):
            
            if input_type == "up" and not voted_question:
                print("up")
                question.votes += 1
                models.QuestionVote.objects.create(user=request.user, question=question, vote_type="up")
                
            elif input_type == "down" and not voted_question:
                print("down")
                question.votes -= 1
                models.QuestionVote.objects.create(user=request.user, question=question, vote_type="down")

            elif input_type == "down" and voted_question and voted_question.vote_type == "down":
                print("already voted down")
                
            elif input_type == "up" and voted_question and voted_question.vote_type == "up":
                print("already voted up")

            elif input_type == "up" and voted_question and voted_question.vote_type == "down":
                question.votes += 1
                models.QuestionVote.objects.filter(user=request.user, question=question).update(vote_type="up")

            elif input_type == "down" and voted_question and voted_question.vote_type == "up":
                question.votes -= 1
                models.QuestionVote.objects.filter(user=request.user, question=question).update(vote_type="down")
                
            question.save()
            
            return redirect('authenticate:question-detail', question_id=question.id)
        
        elif input_type in ("answer-up", "answer-down"):
            answer_id_str = request.POST.get("answer_id")
            if answer_id_str is not None:
                answer_id = int(answer_id_str)
                answer = get_object_or_404(models.Answer, id=answer_id)
                
                voted_answer = models.AnswerVote.objects.filter(user=request.user, answer=answer).first()
                
                if input_type == "answer-up" and not voted_answer:
                    print("answer-up")
                    answer.Likes += 1
                    models.AnswerVote.objects.create(user=request.user, answer=answer, vote_type="answer-up")
                
                elif input_type == "answer-down" and not voted_answer:
                    print("answer-down")
                    answer.Likes -= 1
                    models.AnswerVote.objects.create(user=request.user, answer=answer, vote_type="answer-down")

                elif input_type == "answer-down" and voted_answer and voted_answer.vote_type == "answer-down":
                    print("already voted down")
                    
                elif input_type == "answer-up" and voted_answer and voted_answer.vote_type == "answer-up":
                    print("already voted up")

                elif input_type == "answer-up" and voted_answer and voted_answer.vote_type == "answer-down":
                    answer.Likes += 1
                    models.AnswerVote.objects.filter(user=request.user, answer=answer).update(vote_type="answer-up")

                elif input_type == "answer-down" and voted_answer and voted_answer.vote_type == "answer-up":
                    answer.Likes -= 1
                    models.AnswerVote.objects.filter(user=request.user, answer=answer).update(vote_type="answer-down")

                answer.save()
                return redirect('authenticate:question-detail', question_id=question.id)

        elif input_type == "answer-comment":
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.user = request.user
                comment.answer = get_object_or_404(models.Answer, id=int(request.POST['answer_id']))
                comment.save()
                return redirect(request.META.get('HTTP_REFERER'))

        elif comment_form.is_valid() and input_type == "comment":
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.question = question
            comment.save()
            return redirect('authenticate:question-detail', question_id=question.id)

        elif input_type == "answer":
            if answer_form.is_valid(): 
                answer = answer_form.save(commit=False)
                answer.user = request.user
                answer.question = question
                answer.save()
                return redirect('authenticate:question-detail', question_id=question.id)
            
        elif input_type == "ques-bookmark":
            bookmarked = models.BookMarked.objects.filter(user=request.user, question=question).exists()
            
            if not bookmarked:
                models.BookMarked.objects.create(user=request.user, question=question, isBookMarked=True)
                # bookmark = models.BookMarked.objects.filter(user=request.user, question=question).first()
                print("created the bookmark")
                return redirect('authenticate:question-detail', question_id=question.id)
            else:
                models.BookMarked.objects.filter(user=request.user, question=question).delete()
                print("deleted the bookmark created")
                
                return redirect('authenticate:question-detail', question_id=question.id)
    else:
        print("login required")
        # bookmark=""
    context = {
        'question': question, 
        'answers': answers, 
        'form': comment_form, 
        'answer_form': answer_form,
        'bookmark': bookmark
        }

    return render(request, 'question-detail.html', context)

def saved_view(request):
    if request.user.is_authenticated:
        user_info = models.UserInformation.objects.get(user=request.user)
        bookmarked = models.BookMarked.objects.filter(user=request.user)
        tag_list=[]
        for i in bookmarked:
            print(i.question.Tags)
            
            tag_list.append(i.question.Tags)
        print(tag_list)
        context = {
            "user_info": user_info,
            "bookmarked": bookmarked,
            'tag_list': tag_list,
            'view_template': 'all-saved.html'
        }
        return render(request, 'saved.html', context)
    return redirect("authenticate:login")

def profile_view(request):
    return HttpResponse("profilepage")

def edit_view(request):

stackoverflow/authenticate/templates/answers-body.html
{% load static %}
{% load markdown_filters %}
{% block head %}
    <link rel="stylesheet" href="{% static 'style/authenticate/main-body.css' %}">
    <link rel="stylesheet" href="{% static 'style/authenticate/question-details.css' %}">

{% endblock %}
<div class="page-body">
    <div class="added-modified">
        <div class="top-div">
        <p class="entry-text">
            {{ question.Title}}
        </p>
        <button class="ask-ques-btn" type="button" onclick="goToAskQuestion()">Ask Question</button>
        </div>
        <div class="added-info">
            <p class="asked-at">Asked <span style="color: black; padding-right:15px">{{ question.CreatedAt|timesince:""}}</span></p>
            <p class="modified-at">Modified <span style="color: black; padding-right:15px">{{ question.CreatedAt|timesince:""}}</span></p>
            <p class="views-count">Views <span style="color: black; padding-right:15px">{{ question.views}}</span></p>
        </div>
    </div>

    <div class="question-information">
        <div class="operations-on-ques">
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="input_type" value="up">
                <button type="submit" class="up-vote">
                    <i class="fa-solid fa-caret-up"></i>
                </button>
            </form>

            <div class="vote-count-div">
                {{ question.votes }}
            </div>

            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="input_type" value="down">
                <button type="submit" class="up-vote">
                    <i class="fa-solid fa-caret-down"></i>
                </button>
            </form>
            <div class="bookmark">
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="input_type" value="ques-bookmark">
                    <button type="submit" class="bookmark-btn">
                        {% if request.user.is_authenticated %}
                            {% if bookmark and request.user == bookmark.user %}
                                <i class="fa-solid fa-bookmark q-bookmark" style="color: #ff7800;"></i>
                            {% else %}
                                <i class="fa-regular fa-bookmark q-bookmark" style="color: grey;"></i>
                            {% endif %}
                        {% else %}
                            <i class="fa-regular fa-bookmark q-bookmark" style="color: grey;"></i>
                        {% endif %}
                    </button>
                </form>
                
                
            </div>
            <div class="bookmark timeline">
                <i class="fa-solid fa-clock-rotate-left" style="color: #c0bfbc;"></i>
            </div>
        </div>
        <div class="ques-info">
            <div class="ques-decsription">
                {{ question.Description|markdown|safe }}
            </div>
            <div class="ques-what-u-tried">
                {{ question.what_you_try |markdown|safe}}
            </div>
            <div class="tags-container">
                {% for tag in question.tag_list %}
                    <div class="tag-content">
                        {{ tag }}
                    </div>
                {% endfor %}
            </div>
            <div class="extra-user-info">
                <div class="share-edit">
                    <p>Share</p>
                    <p>Edit</p>
                    <p>Follow</p>
                </div>
                <div class="user-info-stats">
                    Asked {{ question.CreatedAt|timesince:""}}
                    <div class="user-pic-stat">
                        <img src="{% static 'images/icon.png'%}" alt="profile" height="40px" width="40px"/>
                        <div style="padding-left: 7px;">
                            <span style="color: rgb(60, 138, 255);">{{ user.username }}</span>
                            <p>1</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="comment-section">
        {% for comment in question.comment_set.all %}
            <p>{{ comment.Content }} - <span style="color: rgb(126, 126, 255);">{{ comment.user }}</span></p>
        {% endfor %}
    </div>
    <div class="text-comment-input">
        <div class="input-comment">
            <form method="post">
                {% csrf_token %}
                <div class="ques-comment-area">
                    {{ form.Content }}
                    {% if form.Content.errors %}
                    <p>{{ form.Content.errors }}</p>
                    {% endif %}
                </div>
                <input type="hidden" name="input_type" value="comment">
                <button class="ques-comment-btn" onclick="showError()">Post your comment</button>
            </form> 
        </div>
        <p class="add-btn" onclick="showCommentInput()">
            Add a comment
        </p>
    </div>

    <div class="answers-container">
        {% if  question.answer_set.count  > 0 %}
            <div class="answer-header">
                <p> {{question.answer_set.count}} Answers</p>
                <div class="sort-input">
                    <p>Sorted by:</p>
                    <select name="sorting-option" id="sort">
                        <option value="">Highest score (default)</option>
                        <option value="">Trending (recent votes count more)</option>
                        <option value="">Date modified (newest first)</option>
                        <option value="">Date created (oldest first)</option>

                    </select>
                </div>
            </div>
            <div class="answer">
                {% for answer in answers %}
                <div class="answer-card">
                    <div class="operations-on-ques">
                        <form method="post" action="{% url 'authenticate:question-detail' question.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="input_type" value="answer-up">
                            <input type="hidden" name="answer_id" value="{{ answer.id }}">
                            <button type="submit" class="up-vote">
                              <i class="fa-solid fa-caret-up"></i>
                            </button>
                          </form>
                          <div class="vote-count-div">
                            {{ answer.Likes }}
                        </div>
                          <form method="post" action="{% url 'authenticate:question-detail' question.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="input_type" value="answer-down">
                            <input type="hidden" name="answer_id" value="{{ answer.id }}">
                            <button type="submit" class="up-vote">
                              <i class="fa-solid fa-caret-down"></i>
                            </button>
                          </form>
                        <div class="bookmark">
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="input_type" value="ans-bookmark">
                                <button type="submit" class="bookmark-btn">
                                    {% if request.user.is_authenticated %}
                                    {% if request.user != bookmark.user and answer != bookmark.answer %}
                                    <i class="fa-regular fa-bookmark q-bookmark" style="color: grey;"></i>
                                    {% else %}
                                    <i class="fa-solid fa-bookmark q-bookmark" style="color: #ff7800;"></i>
                                    {% endif %}
                                    {% else %}
                                    <i class="fa-regular fa-bookmark q-bookmark"></i>
                                    {% endif %}
                                </button>
                            </form>
                        </div>
                        <div class="bookmark timeline">
                            <i class="fa-solid fa-clock-rotate-left" style="color: #c0bfbc;"></i>
                        </div>
                    </div>
                    <div class="section-two">
                        <div class="ques-info">
                            <div class="ques-decsription">
                                {{ answer.Content|markdown|safe}}
                            </div>
                            <div class="extra-user-info">
                                <div class="share-edit">
                                    <p>Share</p>
                                    <p>Edit</p>
                                    <p>Follow</p>
                                </div>
                                <div class="user-info-stats">
                                    Answered {{ answer.CreatedAt|timesince:""}}
                                    <div class="user-pic-stat">
                                        <img src="{% static 'images/icon.png'%}" alt="profile" height="40px" width="40px"/>
                                        <div style="padding-left: 7px;">
                                            <span style="color: rgb(60, 138, 255);">{{ answer.user }}</span>
                                            <p>1</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="comment-section">
                                {% for comment in answer.comment_set.all %}
                                    <p>{{ comment.Content }} - <span style="color: rgb(126, 126, 255);">{{ comment.user }}</span></p>
                                {% endfor %}
                            </div>
                            <div class="answer-input-comment answer-{{ answer.id }}">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="ans-comment-area">
                                        {{ form.Content }}
                                    </div>
                                    <input type="hidden" name="input_type" value="answer-comment">
                                        <input type="hidden" name="answer_id" value="{{ answer.id }}">
                                    <button class="ques-comment-btn">Post your comment</button>
                                </form>
                                
                            </div>
                            <p class="add-btn" onclick="showAnswerCommentInput('{{answer.id}}')">
                                Add a comment
                            </p>
                        </div>                        
                    </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

    <div class="enter-your-answer">
        <p>Your Answer</p>
        <form method="post">
            {% csrf_token %}
                {{ answer_form.Content }}
            <input type="hidden" name="input_type" value="answer">
            <div class="preview-answer">
                
            </div>
            <button>Post your answer</button>
        </form>
    </div>
    <div class="last-text">
        <p>Not the answer you're looking for? Browse other questions tagged</p>
        <div class="tags-container">
            {% for tag in question.tag_list %}
                <div class="tag-content">
                    {{ tag }}
                </div>
            {% endfor %}
            </div>
            <p>or ask your own question. </p>
        </div>
</div>
<script>
    function goToAskQuestion(){
        window.location = "{% url 'authenticate:ask-question'%}";
    }
    function showCommentInput(){
        document.querySelector('.input-comment').style.display='block';
    }
    function showAnswerCommentInput(clickedItemId){
        let commentForm = document.querySelector(`.answer-${clickedItemId}`);
        if (commentForm) {
            commentForm.style.display = 'block';
        }
    }
    function checkEnter(event) {
        if (event.key === 'Enter') {
            let commentTextarea = document.querySelector('.comment');
            commentTextarea.value = '';
            commentTextarea.style.display = 'none';
        }
    }
    document.addEventListener('mouseup', (event) => {
        const ques_inpt = document.querySelector('.input-comment');
        const ans_inpt = document.querySelectorAll('.answer-input-comment');
        for (let i=0;i<ans_inpt.length;i++){
            if (!ans_inpt[i].contains(event.target)){
                ans_inpt[i].style.display='none';
                }
            }
        if (!ques_inpt || !ques_inpt.contains(event.target)) {
            document.querySelector('.input-comment').style.display = 'none';
        }
    });
    function changeBookmark() {
        let element = document.querySelector('.q-bookmark');
        if (element.style.color === "grey") {
            element.classList.replace("fa-regular", "fa-solid" );
            element.style.color = "#ff7800";
        }
    }
    function changeAnsBookmark(){

    };
</script>

stackoverflow/authenticate/templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <script>
        function goToAskQuestion(){
            console.log("clicked");
            window.location = "{% url 'authenticate:ask-question'%}";
            }
    </script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha512-Avb2QiuDEEvB4bZJYdft2mNjVShBftLdPG8FJ0V7irTLQ8Uo0qcPxh4Plq7G5tGm0rU+1SPhVotteLpBERwTkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'style/authenticate/homepage.css' %}">
{% endblock %}

{% block header %}  

    {% if user.is_authenticated %}
        {% include 'include/logged-header.html' %}
    {% else %}
        {% include 'include/nonlogged-header.html' %}
    {% endif %}  

{% endblock %}

{% block sidebar %}
    {% include 'side-bar.html'   %}
{% endblock %}

{% block main %}
    {% include 'main-body.html' %}
{% endblock %}
    
{% block meta %}
    {% include 'side-pannel.html' %}
{% endblock %}

{% block footer %}
    {% include 'include/footer.html'   %}
{% endblock %}

stackoverflow/authenticate/templates/question-detail.html
{% extends 'base.html' %}

{% comment %}
{{ question.Title }}
{% for answer in question.answer_set.all %}
    <br>{{ answer.Content }}<br>
{% endfor %}
{% endcomment %}

{% load static %}
{% block head %}
    <script>
        function goToAskQuestion(){
            window.location = "{% url 'authenticate:ask-question'%}";
            }
    </script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha512-Avb2QiuDEEvB4bZJYdft2mNjVShBftLdPG8FJ0V7irTLQ8Uo0qcPxh4Plq7G5tGm0rU+1SPhVotteLpBERwTkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'style/authenticate/homepage.css' %}">
    <link rel="stylesheet" href="{% static 'style/authenticate/question-details.css' %}">
{% endblock %}

{% block header %}  

    {% if user.is_authenticated %}
        {% include 'include/logged-header.html' %}
    {% else %}
        {% include 'include/nonlogged-header.html' %}
    {% endif %}  

{% endblock %}

{% block sidebar %}
    {% include 'side-bar.html'   %}
{% endblock %}

{% block main %}
    {% include 'answers-body.html' %}
{% endblock %}
    
{% block meta %}
    {% include 'side-pannel.html' %}
{% endblock %}

{% block footer %}
    {% include 'include/footer.html'   %}
{% endblock %}