stackoverflow/authenticate/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "authenticate"
urlpatterns = [
    path('', views.home_page, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('ask/', views.ask_question_view, name='ask-question'),
    path('question/<int:question_id>/', views.question_detail, name='question-detail'),
    path('saved/', views.saved_view, name='saved-view'),
    
    path('edit/', views.edit_view, name='edit-profile'),
    path('profile/', views.profile_view, name='profile-view'),
    
    path('logout/', views.logout_view, name="logout")
]

stackoverflow/stackoverflow/urls.py
from django.contrib import admin
from django.urls import path, include

from stackoverflow.settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static

urlpatterns = [
    path('', include('authenticate.urls')),
    path('admin/', admin.site.urls),
] + static(MEDIA_URL, document_root = MEDIA_ROOT)

stackoverflow/templates/include/footer.html
<footer>
    <div class="footer-container">
        <div class="stackoverflow-footer">
            <div class="footer-heading">
                <h3>Stack Overflow</h3>
            </div>
            <ul class="footer-list">
                <li><a href="#">Questions</a></li>
                <li><a href="#">Help</a></li>
            </ul>
        </div>

        <div class="stackoverflow-footer">
            <div class="footer-heading">
                <h3>Products</h3>
            </div>
            <ul class="footer-list">
                <li><a href="#">Teams</a></li>
                <li><a href="#">Advertising</a></li>
                <li><a href="#">Collectives</a></li>
                <li><a href="#">Talent</a></li>
            </ul>
        </div>

        <div class="stackoverflow-footer">
            <div class="footer-heading">
                <h3>Company</h3>
            </div>
            <ul class="footer-list">
                <li><a href="#">About</a></li>
                <li><a href="#">Press</a></li>
                <li><a href="#">Work Here</a></li>
                <li><a href="#">Legal</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Terms of Service</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Cookie Settings</a></li>
                <li><a href="#">Cookie Policy</a></li>
            </ul>
        </div>
        <div class="stackoverflow-footer">
            <div class="footer-heading">
                <h3>Stack Exchange Network</h3>
            </div>
            <ul class="footer-list">
                <li><a href="#">Technology</a></li>
                <li><a href="#">Culture & recreation</a></li>
                <li><a href="#">Life & arts</a></li>
                <li><a href="#">Science</a></li>
                <li><a href="#">Professional</a></li>
                <li><a href="#">Business</a></li>
                <li><a href="#">API</a></li>
                <li><a href="#">Data</a></li>
            </ul>
        </div>
        <div class="social-copyright">
            <div class="social">
                <p class="social">Blog</p>
                <p class="social">Facebook</p>
                <p class="social">Twitter</p>
                <p class="social">LinkedIn</p>
                <p class="social">Instagram</p>
            </div>
            <div class="copyright">
                Site design / logo © 2023 Stack Exchange Inc; user contributions licensed under CC BY-SA. rev 2023.11.21.1314
            </div>
        </div>
    </div>
</footer>

stackoverflow/templates/include/logged-header.html
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'logged-nav.css'%}">
{% endblock %}

<header>
    <div class="header-container">
        <div class="header-content">

        <div class="stackflow">
            <a href="/"><img src="{% static 'images/Stack-Overflow-Logo.png' %}"></a>
        </div>
        <div class="options">
            <p class="product" ><a href="#">Products</a></p>
        </div>
        <form method="post" action="{% url 'authenticate:home' %}">
            {% csrf_token %}
            <div class="search-container">
                <div class="search-icon">
                    <img src="{% static 'images/search.png' %}" alt="search icon" height="40px" width="40px">
                </div>
        
                <input type="hidden" class="search-input-value" name="input-value" value="" placeholder="Search...">
                <input type="text" class="search-input" placeholder="Search...">
            </div>
        </form>
        
        <div class="logged-in">
            <img src="{% static 'images/stackoverflow_icon.png' %}"  alt="Profile Picture" height="30px" width="30px" />
            <img src="{% static 'images/inbox.png' %}" alt="inbox" height="25px" width="25px"/>
            <img src="{% static 'images/trophy.png' %}" alt="inbox" height="20px" width="20px"/>
            <img src="{% static 'images/question.png' %}" alt="inbox" height="20px" width="20px"/>
            <button class="stack-exchanfe-dropdown" onclick="toggleMenu()">
                <img src="{% static 'images/stack-exchange-logo.png' %}" alt="inbox" height="20px" width="20px"/>
                <div class="ul-content">
                    <div class="ul-heading">
                        CURRENT COMMUNITY
                    </div>
                    <div class="ul-items-container">
                        <div class="logout-container">
                            <div class="div-one">
                                <img src="{% static 'images/icon.png' %}" alt="logo" height="25px" width="25px">
                            <p>Stackoverflow</p>
                            </div>
                            <div class="div-two">
                                <a>help</a>
                                <a>chat</a>
                                <a href="{% url 'authenticate:logout' %}">log out</a>
                            </div>
                        </div>
                        <div class="meta-stack-over-flow">
                            <i class="fa-solid fa-l"></i>
                            <img src="{% static 'images/stackoverflow_icon.png' %}" alt="logo" height="17px" width="17px">
                            <p>Meta Stack Overflow</p>
                        </div>
                    </div>
                    <div class="ul-heading">
                        YOUR COMMUNITY
                    </div>
                    <div class="div-one your-com">
                        <img src="{% static 'images/icon.png' %}" alt="logo" height="25px" width="25px">
                    <p>Stackoverflow</p>
                    </div>
                </div>
            </button>
        </div>
    </div>
</div>
<script>
    function toggleMenu() {
        var menu = document.querySelector(".ul-content");
        menu.style.display = menu.style.display === "block" ? "none" : "block";
      }
      document.addEventListener('mouseup', function (event) {
        var menuList = document.querySelector(".ul-content");
        var profileButton = document.querySelector('.stack-exchanfe-dropdown');

        if (!menuList.contains(event.target) && !profileButton.contains(event.target)) {
            menuList.style.display = 'none';
        }
    });

    const inputField = document.querySelector(".search-input");
    const hiddenInput = document.querySelector(".search-input-value");

    inputField.addEventListener('input', (event) => {
        const inputValue = event.target.value;
        hiddenInput.value = inputValue;
    });

    inputField.addEventListener('keydown', (event) => {
        if (event.key === 'Enter' || event.keyCode === 13) {
            const inputValue = inputField.value;
            hiddenInput.value = inputValue;

            // Optionally, you can submit the form
            const form = inputField.closest('form');
            if (form) {
                form.submit();
            }
        }
    });
    </script>
</header>

stackoverflow/templates/include/nonlogged-header.html
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'nonlogged-nav.css'%}">
{% endblock %}
<header>
    <div class="header-container">
        <div class="header-content">
         
        <div class="stackflow">
            <a href="/"><img src="{% static 'images/Stack-Overflow-Logo.png' %}"></a>
        </div>
        <div class="options">
            <p class="product" ><a href="#">About</a></p>
            <p class="product" ><a href="#">Products</a></p>
            <p class="product" ><a href="#">For Teams</a></p>
        </div>
        <div class="search-container">
            <div class="search-icon">
                <img src="{% static 'images/search.png' %}" alt="search icon" height="40px" width="40px">
            </div>
            <input type="text" class="search-input" placeholder="Search...">
        </div>
        <div class="logged-out">
            <button class="login-button" onclick="goToLogin()">Log in</button>
            <button class="signup-button" onclick="goToRegister()">Sign up</button>
        </div>
    </div>   
    </div>
</header>
<script>
function goToLogin(){
    window.location = "{% url 'authenticate:login'%}"
}
function goToRegister(){
    window.location = "{% url 'authenticate:register'%}"
}
</script>

stackoverflow/templates/include/question-list.html
{% load static%}
{% block head %}
    <link rel="stylesheet" href="{% static 'question-list.css' %}">
{% endblock %}
{% block questionlist %}
    <div class="question-list-container">
        {% for question in questions %}
        
        <div class="question-container">

            <div class="question-meta">
                <p class="votes">
                    {{ question.votes }} votes
                </p>
                <p class="answers">
                    {% if question.answer_count > 0 %}
                    <div class="gt_zero">
                        {{ question.answer_count }} answers
                    </div>
                    
                    {% else %}
                    {{ question.answer_count }} answers
                    {% endif %}
                </p>
                <p class="view">
                    {{ question.views }} views
                </p>
            </div>

            <div class="question-title">
                <div class="title-text">
                    <a href="{% url 'authenticate:question-detail' question.id %}">{{ question.Title }}</a>
                </div>
                <div class="tag-timestamp">
                    <div class="tags-container">
                        {% for tag in question.tag_list %}
                            <div class="tag-content">
                                {{ tag }}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="posted_at">
                        <img src="{% static 'images/bookmark.png'%}" alt="profile image here"
                        style="width:15px;height:15px; padding-right:6px">
                        {{ question.user }}
                        <p class="reputation"> 2 </p>
                        <p class="ago">asked {{ question.CreatedAt|timesince }} ago</p>
                    </div>
                </div>
                
            </div>
        </div>
    {% endfor %}
    <p class="last-text">
        Looking for more? Browse the <span style="color: rgb(88, 88, 255); cursor: pointer;">complete list of questions</span>, or <span style="color: rgb(88, 88, 255);cursor: pointer;">popular tags</span>. Help us answer <span style="color: rgb(88, 88, 255);cursor: pointer;">unanswered questions</span>.
    </p>
    </div>
{% endblock %}